export type Locale = "ko" | "en";

export const copy = {
  ko: {
    localeName: "한국어",
    switchLabel: "EN",
    switchHref: "/en",
    nav: { work: "프로젝트", approach: "일하는 방식", career: "경력", recognition: "수상·활동", contact: "연락하기" },
    hero: {
      eyebrow: "Founder-minded, AI-native Product Owner",
      title: "Junseok Kim",
      body: "전기차 충전, 글로벌 커머스, AI 제품을 만들며 문제 정의부터 출시와 운영 성과까지 책임져 왔습니다. AI를 제품 개발 과정에 연결해 소수정예 팀의 실행 속도를 높이는 Product Owner 김준석입니다.",
      primary: "대표 프로젝트 보기",
      secondary: "LinkedIn",
    },
    impacts: [
      { value: "2주→1주", label: "제품 배포 주기", note: "기획·개발·품질 검증 병렬 실행" },
      { value: "약 4배", label: "1인당 제품 개발 생산성", note: "사용자 제공 산식 기반 추정" },
      { value: "+582%", label: "영국 외 국가 매출", note: "글로벌 판매 운영 확장" },
      { value: "Winner", label: "L’Oréal BigBang 2025", note: "디지털 부문" },
    ],
    approach: {
      eyebrow: "PRODUCT OPERATING MODEL",
      title: "문제 정의에서 운영 성과까지",
      intro: "전략 문서에서 멈추지 않고, 제품의 의사결정과 구현·배포·측정을 하나의 흐름으로 연결합니다.",
      items: [
        ["01", "문제 정의", "데이터·고객 의견·인터뷰를 함께 살펴 반복되는 증상보다 해결해야 할 근본 원인을 찾습니다."],
        ["02", "제품 빌딩", "기능 요구사항과 화면 동작을 문서로 명확히 정리하고, AI·프로토타입·코드로 빠르게 구현합니다."],
        ["03", "성과 확장", "출시 이후 운영과 사업의 핵심지표를 확인하고, 다음 제품에도 적용할 수 있는 방식으로 정리합니다."],
      ],
    },
    selected: "대표 프로젝트",
    projectIntro: "각 사례에서 어떤 제품을 맡았고, 무엇을 바꾸었으며, 어떤 결과를 만들었는지 순서대로 설명합니다.",
    projects: [
      {
        id: "ai-dlc",
        company: "EVAR · 2026",
        label: "FLAGSHIP · DELIVERY SYSTEM",
        title: "AI 기반 주 1회 제품 배포 체계 구축",
        summary: "전기차 충전 결제 서비스 EV PAY와 충전기 관리 SaaS NOVA의 기획·디자인·개발·품질 검증이 하나의 제품 명세를 기준으로 동시에 움직이도록 개발 방식을 재설계했습니다.",
        bullets: ["358개 기능 요구사항을 하나의 시스템에서 관리", "공통 기준을 적용해 주요 기획 누락 90% 이상 감소", "2주 단위 개발을 매주 배포하는 체계로 전환"],
        image: "/img/portfolio/evar/ai-dlc-before-after.png",
        imageAlt: "사람 중심 2주 스프린트에서 AI 중심 1주 스프린트로 전환한 개발 구조",
        metric: "약 4배",
        metricLabel: "1인당 제품 개발 생산성 추정",
      },
      {
        id: "nova",
        company: "EVAR · 2026",
        label: "B2B SAAS · PRODUCT OWNERSHIP",
        title: "전기차 충전기 관리 SaaS의 멀티 고객사 제품 전환",
        summary: "기존 충전기 관리 솔루션 EV Square를 후속 제품 NOVA로 개편했습니다. 여러 충전 사업자가 함께 사용할 수 있도록 대시보드, 충전기 제어, 매출·정산, 사용자 권한을 다시 설계했습니다.",
        bullets: ["충전기 상태를 2개에서 7개로 세분화해 운영 판단 개선", "매출과 충전기 운영 핵심지표를 한 화면에 통합", "국내·미국·일본 고객사 전환과 운영 효율 약 30% 향상 기반 구축"],
        image: "/img/portfolio/evar/nova-dashboard-before-after.png",
        imageAlt: "EVSquare 1.0과 NOVA 대시보드 비교",
        metric: "358",
        metricLabel: "통합 관리 기능 요구사항",
      },
      {
        id: "ai-call-center",
        company: "EVAR · IN PROGRESS",
        label: "AI PRODUCT · DOMAIN ONTOLOGY",
        title: "전기차 충전 고객 문의의 맥락을 이해하는 AI 설계",
        summary: "충전기, 모바일 앱, 운영 매뉴얼을 하나의 지식 체계로 묶고 회원·인증 수단·충전기·결제 기록의 관계를 구조화해 고객 문의의 원인을 단계적으로 찾도록 설계했습니다.",
        bullets: ["AI 기반 고객지원 플랫폼 사업 태스크포스 리드", "고객 정보와 충전 기록 사이의 조회 관계 설계", "현재 개발 중인 제품으로 성과 수치는 아직 표기하지 않음"],
        image: "",
        imageAlt: "내부 엔터티와 판단 규칙을 제외한 EV 충전 고객지원 온톨로지 공개용 개념도",
        metric: "Ontology",
        metricLabel: "충전 도메인 지식 구조",
      },
      {
        id: "hands-on",
        company: "EVAR · 2026",
        label: "HANDS-ON BUILDING",
        title: "글로벌 기업 웹사이트와 충전기 커스텀 도구 직접 출시",
        summary: "전기차 충전 기업 EVAR의 한국·미국·일본 웹사이트를 직접 개발하고, 고객이 충전기 외관을 편집하는 웹 도구 Sticker Studio를 2주 만에 출시했습니다.",
        bullets: ["KR·EN·JP 글로벌 홈페이지 구축", "인바운드 리드 2배 이상", "구매자의 약 25%가 스티커 옵션 추가"],
        image: "/img/portfolio/evar/sticker-studio.png",
        imageAlt: "EVAR Sticker Studio 편집 화면",
        metric: "2주",
        metricLabel: "Sticker Studio 출시",
      },
      {
        id: "commerce",
        company: "SOOJIB · 2025",
        label: "CROSS-BORDER COMMERCE · 0→1",
        title: "6개국 이상 글로벌 판매 운영 체계 구축",
        summary: "온라인몰 Shopify 주문부터 DHL·FedEx 국제배송, 국가·중량별 배송비, 유럽 수입부가세 신고 제도(IOSS) 대응까지 해외 판매 운영을 처음부터 구축했습니다.",
        bullets: ["2024년 대비 2025년 연간 매출 약 3배 성장", "영국 외 국가에서 발생한 매출 582% 증가", "업무 매뉴얼을 제작해 공급망 운영 담당자에게 인계"],
        image: "",
        imageAlt: "개인정보와 상업 정보를 제외한 글로벌 커머스 운영 흐름 및 매출 성장 지표",
        metric: "3×",
        metricLabel: "2024→2025 연간 매출",
      },
      {
        id: "sefy",
        company: "SOOJIB · 2025",
        label: "AI BEAUTY · GLOBAL POC",
        title: "L’Oréal·3CE 협업 가상 메이크업 AI 제품 기획",
        summary: "사용자가 아이돌의 메이크업을 자신의 얼굴에 가상으로 적용해 보는 제품 SEFY를 기획하고, L’Oréal 한국·중국 법인, 3CE, 개발팀 사이에서 시험 제품의 범위와 일정을 조율했습니다.",
        bullets: ["생성형 이미지 기술을 활용한 가상 메이크업 경험 설계", "중국 현지 시연을 포함한 글로벌 시험 운영", "L’Oréal BigBang 2025 디지털 부문 Winner 수상"],
        image: "/img/portfolio/soojib/sefy-flow.png",
        imageAlt: "SEFY 아이돌 메이크업 가상 체험 제품 흐름",
        metric: "Winner",
        metricLabel: "L’Oréal BigBang 2025",
      },
      {
        id: "mycle",
        company: "마카롱팩토리 · 2024",
        label: "B2B GROWTH · PARTNER PRODUCT",
        title: "자동차 정비소 입점 신청 전환율 361% 개선",
        summary: "차량관리 앱 MYCLE에 정비소가 입점하는 과정을 개선했습니다. 무료 고객 유치 혜택, 입점 안내 페이지, 영업 고객관리, 운영 담당자의 역할을 하나의 흐름으로 연결했습니다.",
        bullets: ["방문자 대비 입점 신청 전환율 361% 증가", "제휴 정비소 약 1,000개에서 1,700개로 확대", "엔진오일 서비스 거래 매출 200억원에서 300억원으로 성장"],
        image: "/img/portfolio/macarong/partner-landing.jpg",
        imageAlt: "마이클 파트너 입점 신청 화면",
        metric: "+70%",
        metricLabel: "파트너 네트워크",
      },
    ],
    moreTitle: "제품 오너십의 기반",
    more: [
      { period: "2021.06–2024.01", company: "어텀팔콘스", role: "Founder / Product Lead", desc: "93개의 고객 문제를 정의하고 15회 이상 초기 제품과 사업 방향을 검증했습니다. 캠핑 커뮤니티 Klang은 사용자 4,000명·평균 체류 17분, 공동구매 서비스 FEED100은 구매 행동 전환율 65%를 기록했습니다.", image: "/img/portfolio/founder/klang.jpg", alt: "Klang 커뮤니티 제품 화면" },
      { period: "2020.08–2021.06", company: "현대자동차", role: "시스템 개발 PM", desc: "그랜저(GN7) 디지털 계기판 플랫폼의 요구사항·협력사 이슈를 관리하고 Python 테스트 자동화로 검증 시간 20% 단축.", image: "/img/portfolio/hyundai/gn7-cluster.jpg", alt: "현대자동차 GN7 디지털 클러스터" },
      { period: "2024", company: "MYCLE 파트너 품질관리", role: "Quality System & Product Operations", desc: "제휴 정비소의 서비스 품질을 측정하는 지표(PQI)를 설계하고 재고·정산 앱을 개선해 파트너 문의와 불만을 33.3% 줄이고 품질지표를 16% 높였습니다.", image: "/img/mycle-pqi.png", alt: "MYCLE 파트너 품질지표 PQI 대시보드" },
      { period: "2025", company: "SOOJIB New Business", role: "Zero-to-One Business Development", desc: "EU 뷰티 인증 대행과 K-pop OST 공급망 신사업을 시장 조사부터 물류 구조 설계와 출시까지 주도했습니다.", image: "/img/soojib-public.jpg", alt: "SOOJIB 신규 사업 공개 이미지" },
    ],
    careerTitle: "자동차 시스템 개발에서 AI 제품 책임자로",
    careerIntro: "자동차 소프트웨어 개발로 기술 기반을 쌓고, 창업·기업용 제품 성장·글로벌 AI 사업화를 거쳐 현재는 AI를 활용한 제품 개발 체계를 이끌고 있습니다.",
    careers: [
      ["2026.01–현재", "EVAR", "전기차 충전 서비스 Product Owner → AI 플랫폼 사업 태스크포스 리드"],
      ["2025.01–2026.01", "SOOJIB", "AI Product Owner & Business Development"],
      ["2024.01–2024.09", "마카롱팩토리", "파트너 전략팀 PO Lead"],
      ["2021.06–2024.01", "어텀팔콘스", "Founder / Product Lead"],
      ["2020.08–2021.06", "현대자동차", "시스템 개발 PM"],
    ],
    collaborations: "함께 일하고 성과를 만든 조직",
    capabilities: {
      eyebrow: "FOUNDATION & TOOLS",
      title: "제품 기획을 실제 구현과 데이터 분석까지 연결하는 도구",
      groups: [
        { label: "AI", items: ["Claude Code", "Codex", "Ollama"] },
        { label: "TOOLS & TECH", items: ["SQL", "Python", "GA4", "Figma", "Notion"] },
        { label: "WAYS OF WORKING", items: ["Agile / Sprint", "Lean Startup", "Data-informed"] },
      ],
      educationLabel: "EDUCATION",
      educationTitle: "UNIST · 울산과학기술원",
      educationDesc: "기계항공공학 전공",
    },
    recognition: {
      eyebrow: "RECOGNITION & LEADERSHIP",
      title: "제품·기술·팀 활동 등 다양한 영역에서 증명한 실행력",
      intro: "AI 뷰티 제품의 글로벌 사업화, 모빌리티 기술 해커톤, 대학 조정대회까지 서로 다른 과제를 맡아 팀과 함께 결과를 만든 경험입니다.",
      items: [
        { year: "2025", type: "PRODUCT AWARD", title: "L’Oréal BigBang 2025 · Digital Winner", desc: "AI 가상 메이크업 제품의 3CE 협업과 글로벌 시험 운영을 이끌어 디지털 부문 Winner로 선정됐습니다.", image: "/img/bigbang-startup.jpg", alt: "L’Oréal BigBang 2025 수상 현장", href: "https://www.loreal.com/ko-kr/korea/loreal-korea-news/press-releases/bigbang-startup-partnership-2025/", link: "공식 기사" },
        { year: "2017", type: "TECH AWARD", title: "Hyundai Hack A Road · 1위", desc: "초보 운전자를 위한 실시간 차량 데이터 조언 시스템을 기획하고 Python 데모를 구현해 대상을 수상했습니다.", image: "/img/hyundai_hack_a_road.jpg", alt: "현대자동차 Hack A Road 수상", href: "https://www.ksilbo.co.kr/news/articleView.html?idxno=621362", link: "관련 기사" },
        { year: "2016", type: "TEAM LEADERSHIP", title: "제11회 대학조정대회 · 종합 3위", desc: "UNIST 조정부 활동을 통해 제11회 대학조정대회에 출전했고, 팀과 함께 대학 종합 3위를 달성했습니다.", image: "/img/rowing.jpg", alt: "UNIST 조정부 대학조정대회 출전 팀", href: "https://news.unist.ac.kr/kor/20160802-03/", link: "UNIST 기사" },
      ],
    },
    closing: {
      eyebrow: "WHY JUNSEOK KIM",
      title: "소수정예 팀의 제품 실행과 비즈니스 성과",
      body: "문제를 선명하게 정의하고 필요한 것을 직접 만듭니다. 출시한 뒤에는 운영 지표로 돌아가 다음 결정을 내립니다.",
      button: "대화 시작하기",
    },
    footnote: "성과 수치는 Career DB의 검증 자료와 사용자 제공 스냅샷을 기준으로 작성했습니다.",
  },
  en: {
    localeName: "English",
    switchLabel: "KO",
    switchHref: "/",
    nav: { work: "Work", approach: "Approach", career: "Career", recognition: "Recognition", contact: "Contact" },
    hero: {
      eyebrow: "Founder-minded, AI-native Product Owner",
      title: "Junseok Kim",
      body: "I have taken products in EV charging, global commerce, and applied AI from problem definition through launch and operations. I use AI across the delivery process to help lean teams move faster without losing rigor.",
      primary: "View selected work",
      secondary: "LinkedIn",
    },
    impacts: [
      { value: "2w→1w", label: "Product release cycle", note: "Planning, engineering, and quality checks in parallel" },
      { value: "~4×", label: "Delivery per person", note: "Estimate based on user-provided inputs" },
      { value: "+582%", label: "Non-UK sales", note: "Cross-border operations expansion" },
      { value: "Winner", label: "L’Oréal BigBang 2025", note: "Digital category" },
    ],
    approach: {
      eyebrow: "PRODUCT OPERATING MODEL",
      title: "From problem definition to operating impact",
      intro: "I go beyond strategy documents by connecting product decisions, implementation, release, and measurement in one delivery loop.",
      items: [
        ["01", "Define", "Combine product data, customer feedback, and interviews to find the root cause behind recurring symptoms."],
        ["02", "Build", "Turn product requirements and interface behavior into a clear specification, then build with AI, prototypes, and code."],
        ["03", "Scale", "Measure operating and business outcomes after launch, then turn what worked into a repeatable product system."],
      ],
    },
    selected: "Selected work",
    projectIntro: "Each case explains the product, my ownership, what changed, and the outcome—without assuming prior knowledge of the company or its tools.",
    projects: [
      {
        id: "ai-dlc", company: "EVAR · 2026", label: "FLAGSHIP · DELIVERY SYSTEM", title: "An AI-enabled delivery system for weekly product releases",
        summary: "I redesigned how EVAR builds its EV charging payment service, EV PAY, and charger-management SaaS, NOVA. Product, design, engineering, and QA now work in parallel from one shared product specification.",
        bullets: ["Managed 358 product requirements in one system", "Reduced major planning omissions by more than 90% through shared standards", "Moved from two-week development cycles to weekly releases"],
        image: "/img/portfolio/evar/ai-dlc-before-after.png", imageAlt: "Transition from a human-centered two-week sprint to an AI-centered weekly sprint", metric: "~4×", metricLabel: "Estimated product delivery per person",
      },
      {
        id: "nova", company: "EVAR · 2026", label: "B2B SAAS · PRODUCT OWNERSHIP", title: "EV charger-management software for multiple operators",
        summary: "I led the transition from EV Square, an EV charger-management tool, to its successor NOVA. I redesigned the dashboard, charger controls, revenue and settlement flows, and user permissions so multiple charging operators could use the product.",
        bullets: ["Expanded charger status from 2 to 7 states for clearer operating decisions", "Combined revenue and charger-operations metrics in one dashboard", "Built the foundation for migrations in Korea, the US, and Japan and an estimated 30% efficiency gain"],
        image: "/img/portfolio/evar/nova-dashboard-before-after.png", imageAlt: "Comparison of the EVSquare 1.0 and NOVA dashboards", metric: "358", metricLabel: "Product requirements managed together",
      },
      {
        id: "ai-call-center", company: "EVAR · IN PROGRESS", label: "AI PRODUCT · KNOWLEDGE MODEL", title: "AI designed to understand the context behind EV charging support requests",
        summary: "I brought charger, mobile-app, and operations documentation into one knowledge model. It connects customer accounts, authentication methods, chargers, charging sessions, and payments so the system can trace the likely cause of a support request.",
        bullets: ["Lead for the AI customer-support platform task force", "Designed lookup relationships between customer and charging records", "Product in development; no outcome metric claimed yet"],
        image: "", imageAlt: "Public abstraction of an EV charging support ontology with internal entities and decision rules omitted", metric: "Ontology", metricLabel: "Charging-domain knowledge layer",
      },
      {
        id: "hands-on", company: "EVAR · 2026", label: "HANDS-ON BUILDING", title: "Shipping a global website and an EV charger customization tool",
        summary: "I built the Korean, US, and Japanese websites for EV charging company EVAR, then shipped Sticker Studio—a web tool that lets customers customize a charger’s exterior—in two weeks.",
        bullets: ["Korean, English, and Japanese site delivery", "More than 2× inbound leads", "~25% of buyers added the sticker option"],
        image: "/img/portfolio/evar/sticker-studio.png", imageAlt: "EVAR Sticker Studio editor", metric: "2 weeks", metricLabel: "Sticker Studio launch",
      },
      {
        id: "commerce", company: "SOOJIB · 2025", label: "CROSS-BORDER COMMERCE · 0→1", title: "Cross-border commerce operations across six-plus markets",
        summary: "I built the full operating flow from Shopify orders to DHL and FedEx shipping, country- and weight-based delivery rates, and IOSS reporting for EU import VAT.",
        bullets: ["Annual sales grew approximately 3× from 2024 to 2025", "Sales outside the UK increased 582%", "Documented the process and handed it over to the supply-chain operations team"],
        image: "", imageAlt: "Public summary of the cross-border commerce workflow and growth metrics with personal and commercial details removed", metric: "3×", metricLabel: "Annual sales, 2024→2025",
      },
      {
        id: "sefy", company: "SOOJIB · 2025", label: "AI BEAUTY · GLOBAL PILOT", title: "An AI virtual makeup product with L’Oréal and 3CE",
        summary: "I designed SEFY, a product that lets users try a K-pop artist’s makeup look on their own face. I aligned the pilot scope and schedule across L’Oréal Korea and China, 3CE, and our engineering team.",
        bullets: ["Designed the virtual makeup experience using generative image technology", "Coordinated a global pilot including an on-site demonstration in China", "Won the Digital category at L’Oréal BigBang 2025"],
        image: "/img/portfolio/soojib/sefy-flow.png", imageAlt: "SEFY virtual idol makeup product flow", metric: "Winner", metricLabel: "L’Oréal BigBang 2025",
      },
      {
        id: "mycle", company: "MYCLE · 2024", label: "B2B GROWTH · PARTNER PRODUCT", title: "A 361% increase in auto-repair shop applications",
        summary: "I improved how repair shops joined MYCLE, a vehicle-maintenance app. I connected the free customer-acquisition offer, application page, sales pipeline, and operations ownership into one partner journey.",
        bullets: ["Visitor-to-application conversion increased 361%", "Partner repair shops grew from roughly 1,000 to 1,700", "Engine-oil service transaction revenue grew from KRW 20B to 30B"],
        image: "/img/portfolio/macarong/partner-landing.jpg", imageAlt: "MYCLE partner application experience", metric: "+70%", metricLabel: "Partner network growth",
      },
    ],
    moreTitle: "Foundations of product ownership",
    more: [
      { period: "2021.06–2024.01", company: "Autumn Falcons", role: "Founder / Product Lead", desc: "Defined 93 customer problems and ran more than 15 early-product and business-model experiments. Klang, a camping community, reached 4,000 users and 17 minutes average time spent; group-buying service FEED100 reached a 65% purchase-action conversion rate.", image: "/img/portfolio/founder/klang.jpg", alt: "Klang community product interface" },
      { period: "2020.08–2021.06", company: "Hyundai Motor Company", role: "System Development PM", desc: "Managed requirements and supplier issues for the Grandeur (GN7) digital cluster platform and reduced repeated validation time by 20% through Python automation.", image: "/img/portfolio/hyundai/gn7-cluster.jpg", alt: "Hyundai Grandeur GN7 digital cluster" },
      { period: "2024", company: "MYCLE Partner Quality", role: "Quality System & Product Operations", desc: "Designed a quality index for partner repair shops and improved their inventory and settlement app, reducing partner questions and complaints by 33.3% while raising the quality score by 16%.", image: "/img/mycle-pqi.png", alt: "MYCLE Partner Quality Index dashboard" },
      { period: "2025", company: "SOOJIB New Business", role: "Zero-to-One Business Development", desc: "Led two new businesses—EU beauty compliance services and a K-pop OST supply chain—from market research through logistics design and launch.", image: "/img/soojib-public.jpg", alt: "Public visual from a SOOJIB new-business launch" },
    ],
    careerTitle: "From automotive systems engineering to AI product ownership",
    careerIntro: "I built my technical foundation in automotive software, then expanded through entrepreneurship, B2B product growth, and global AI commercialization. Today, I lead product delivery systems that use AI across the development process.",
    careers: [
      ["2026.01–Present", "EVAR", "EV charging Product Owner → AI Platform Business Task Force Lead"],
      ["2025.01–2026.01", "SOOJIB", "AI Product Owner & Business Development"],
      ["2024.01–2024.09", "MYCLE", "Partner Strategy PO Lead"],
      ["2021.06–2024.01", "Autumn Falcons", "Founder / Product Lead"],
      ["2020.08–2021.06", "Hyundai Motor Company", "System Development PM"],
    ],
    collaborations: "Organizations I have worked with",
    capabilities: {
      eyebrow: "FOUNDATION & TOOLS",
      title: "Tools that connect product planning to implementation and analysis",
      groups: [
        { label: "AI", items: ["Claude Code", "Codex", "Ollama"] },
        { label: "TOOLS & TECH", items: ["SQL", "Python", "GA4", "Figma", "Notion"] },
        { label: "WAYS OF WORKING", items: ["Agile / Sprint", "Lean Startup", "Data-informed"] },
      ],
      educationLabel: "EDUCATION",
      educationTitle: "UNIST · Ulsan National Institute of Science and Technology",
      educationDesc: "Mechanical and Aerospace Engineering",
    },
    recognition: {
      eyebrow: "RECOGNITION & LEADERSHIP",
      title: "Execution across product, technology, and team leadership",
      intro: "These experiences span the commercialization of an AI beauty product, a mobility technology hackathon, and an inter-university rowing competition—different settings where I worked with a team to deliver a clear result.",
      items: [
        { year: "2025", type: "PRODUCT AWARD", title: "L’Oréal BigBang 2025 · Digital Winner", desc: "Led the 3CE collaboration and global pilot for an AI virtual makeup product, earning the Digital category award.", image: "/img/bigbang-startup.jpg", alt: "L’Oréal BigBang 2025 award ceremony", href: "https://www.loreal.com/ko-kr/korea/loreal-korea-news/press-releases/bigbang-startup-partnership-2025/", link: "Official article" },
        { year: "2017", type: "TECH AWARD", title: "Hyundai Hack A Road · 1st Place", desc: "Designed a real-time vehicle-data guidance system for novice drivers and implemented its Python demo, winning the grand prize.", image: "/img/hyundai_hack_a_road.jpg", alt: "Hyundai Hack A Road award", href: "https://www.ksilbo.co.kr/news/articleView.html?idxno=621362", link: "Read article" },
        { year: "2016", type: "TEAM LEADERSHIP", title: "11th Inter-University Rowing Competition · 3rd Overall", desc: "Competed as part of the UNIST rowing team and helped the university finish third overall.", image: "/img/rowing.jpg", alt: "UNIST rowing team at the inter-university competition", href: "https://news.unist.ac.kr/kor/20160802-03/", link: "UNIST article" },
      ],
    },
    closing: {
      eyebrow: "WHY JUNSEOK KIM",
      title: "Product execution and business outcomes for lean teams",
      body: "I clarify the problem, build what the team needs, and use operating data to decide what comes next.",
      button: "Start a conversation",
    },
    footnote: "Metrics are based on verified Career DB evidence and dated user-provided snapshots.",
  },
} as const;
