export type Locale = "ko" | "en";

export const copy = {
  ko: {
    localeName: "한국어",
    switchLabel: "EN",
    switchHref: "/en",
    nav: { work: "프로젝트", approach: "일하는 방식", career: "경력", recognition: "수상·활동", contact: "연락하기" },
    hero: {
      eyebrow: "Founder-minded, AI-native Product Owner",
      title: "Junseok Kim",
      body: "AI를 제품 개발 과정에 연결해 소수정예 팀의 실행력을 높입니다. 문제 정의부터 출시와 운영 성과까지 직접 책임지는 Product Owner 김준석입니다.",
      primary: "대표 프로젝트 보기",
      secondary: "LinkedIn",
      status: "EVAR · AX Platform 사업 T/F Lead",
    },
    impacts: [
      { value: "2주→1주", label: "AI-DLC 배포 주기", note: "기획·개발·QA 병렬 실행" },
      { value: "약 4배", label: "인당 딜리버리 생산성", note: "사용자 제공 산식 기반 추정" },
      { value: "+582%", label: "영국 외 국가 매출", note: "글로벌 판매 운영 확장" },
      { value: "Winner", label: "L’Oréal BigBang 2025", note: "디지털 부문" },
    ],
    approach: {
      eyebrow: "PRODUCT OPERATING MODEL",
      title: "문제 정의에서 운영 성과까지",
      intro: "전략 문서에서 멈추지 않고, 제품의 의사결정과 구현·배포·측정을 하나의 흐름으로 연결합니다.",
      items: [
        ["01", "문제 정의", "데이터·VoC·인터뷰를 결합해 반복되는 증상보다 해결해야 할 구조를 찾습니다."],
        ["02", "제품 빌딩", "User Story와 HTML Spec으로 결정을 명시하고 AI·프로토타입·코드로 실행합니다."],
        ["03", "성과 확장", "릴리즈 이후 운영·사업 KPI를 확인해 재사용 가능한 제품 시스템으로 만듭니다."],
      ],
    },
    selected: "대표 프로젝트",
    projectIntro: "현재 역할과 가장 가까운 사례부터, 제품 오너십이 축적된 흐름으로 구성했습니다.",
    projects: [
      {
        id: "ai-dlc",
        company: "EVAR · 2026",
        label: "FLAGSHIP · DELIVERY SYSTEM",
        title: "인력 감소 이후에도 주 1회 배포 정착",
        summary: "EV PAY와 충전 운영 백오피스(NOVA)의 기획·디자인·개발·QA가 같은 HTML Spec을 보는 AI-DLC 체계를 설계했습니다.",
        bullets: ["358건 User Story 통합 관리", "기획 누락 90% 이상 감소", "2주 스프린트를 주 1회 배포 체계로 전환"],
        image: "/img/portfolio/evar/ai-dlc-before-after.png",
        imageAlt: "사람 중심 2주 스프린트에서 AI 중심 1주 스프린트로 전환한 개발 구조",
        metric: "약 4배",
        metricLabel: "인당 딜리버리 생산성 추정",
      },
      {
        id: "nova",
        company: "EVAR · 2026",
        label: "B2B SAAS · PRODUCT OWNERSHIP",
        title: "충전 운영 도구를 멀티 고객사형 SaaS로",
        summary: "NOVA 리드 PM으로 대시보드·충전 관리·매출·정산·권한 흐름을 재설계하고 국내·미국·일본 고객 전환 기반을 구축했습니다.",
        bullets: ["운영 상태 2개에서 7개로 세분화", "매출·운영 KPI를 한 화면에 통합", "운영 효율 약 30% 향상(사용자 제공)"],
        image: "/img/portfolio/evar/nova-dashboard-before-after.png",
        imageAlt: "EVSquare 1.0과 NOVA 대시보드 비교",
        metric: "358",
        metricLabel: "통합 관리 User Story",
      },
      {
        id: "ai-call-center",
        company: "EVAR · IN PROGRESS",
        label: "AI PRODUCT · DOMAIN ONTOLOGY",
        title: "문서 검색을 넘어 문의 맥락을 판별하는 AI",
        summary: "하드웨어·앱·충전 운영 매뉴얼을 한데 모으고 회원, 인증 수단, 충전 설비, 결제 이벤트의 관계를 온톨로지로 구조화했습니다.",
        bullets: ["AX Platform 사업 T/F 리드", "도메인 엔터티와 조회 규칙 연결", "진행 중 과제로 성과 수치 미표기"],
        image: "",
        imageAlt: "내부 엔터티와 판단 규칙을 제외한 EV 충전 고객지원 온톨로지 공개용 개념도",
        metric: "Ontology",
        metricLabel: "충전 도메인 지식 구조",
      },
      {
        id: "hands-on",
        company: "EVAR · 2026",
        label: "HANDS-ON BUILDING",
        title: "기획에서 코드와 배포까지 직접 연결",
        summary: "AI 기반 바이브 코딩으로 글로벌 홈페이지를 단독 개발하고, 충전기 커스텀 편집 서비스 Sticker Studio를 2주 만에 출시했습니다.",
        bullets: ["KR·EN·JP 글로벌 홈페이지 구축", "인바운드 리드 2배 이상", "구매자의 약 25%가 스티커 옵션 추가"],
        image: "/img/portfolio/evar/sticker-studio.png",
        imageAlt: "EVAR Sticker Studio 편집 화면",
        metric: "2주",
        metricLabel: "Sticker Studio 출시",
      },
      {
        id: "commerce",
        company: "SOOJIB · 2025",
        label: "CROSS-BORDER COMMERCE · 0→1",
        title: "6개국 이상을 연결한 글로벌 판매 운영 체계",
        summary: "Shopify 주문부터 DHL·FedEx 배송, 국가·중량별 요율, 유럽 IOSS 관부가세 대응까지 해외 판매에 필요한 운영 흐름을 처음부터 구축했습니다.",
        bullets: ["연간 매출 약 3배 성장", "영국 외 국가 매출 +582%", "운영 매뉴얼 제작과 SCM 담당자 이관"],
        image: "",
        imageAlt: "개인정보와 상업 정보를 제외한 글로벌 커머스 운영 흐름 및 매출 성장 지표",
        metric: "3×",
        metricLabel: "2024→2025 연간 매출",
      },
      {
        id: "sefy",
        company: "SOOJIB · 2025",
        label: "AI BEAUTY · GLOBAL POC",
        title: "AI 뷰티 기술을 브랜드 협업 제품으로",
        summary: "아이돌 포토카드 이미지를 활용한 가상 메이크업 경험을 기획하고 L’Oréal Korea·China, 3CE, 개발팀 사이의 제품 요구사항과 PoC를 조율했습니다.",
        bullets: ["GAN 기반 가상 메이크업 제품 기획", "글로벌 파트너십·PoC 운영", "L’Oréal BigBang 2025 디지털 부문 Winner"],
        image: "/img/portfolio/soojib/sefy-flow.png",
        imageAlt: "SEFY 아이돌 메이크업 가상 체험 제품 흐름",
        metric: "Winner",
        metricLabel: "L’Oréal BigBang 2025",
      },
      {
        id: "mycle",
        company: "마카롱팩토리 · 2024",
        label: "B2B GROWTH · PARTNER PRODUCT",
        title: "96.7%가 이탈하던 입점 퍼널을 성장 시스템으로",
        summary: "무료 고객 유치 USP, 입점 랜딩, CRM과 운영 R&R을 연결해 파트너 확보와 거래 성장을 만들었습니다.",
        bullets: ["세션→입점 신청 전환 +361%", "파트너 네트워크 약 1,000→1,700개", "엔진오일 거래 매출 200억→300억원"],
        image: "/img/portfolio/macarong/partner-landing.jpg",
        imageAlt: "마이클 파트너 입점 신청 화면",
        metric: "+70%",
        metricLabel: "파트너 네트워크",
      },
    ],
    moreTitle: "제품 오너십의 기반",
    more: [
      { period: "2021.06–2024.01", company: "어텀팔콘스", role: "Founder / Product Lead", desc: "93개 문제 정의, 15회 이상 MVP·피벗. Klang 4,000명·평균 체류 17분, FEED100 CTA 전환율 65%." },
      { period: "2020.08–2021.06", company: "현대자동차", role: "시스템 개발 PM", desc: "그랜저(GN7) 디지털 계기판 플랫폼의 요구사항·협력사 이슈를 관리하고 Python 테스트 자동화로 검증 시간 20% 단축." },
    ],
    careerTitle: "시스템 엔지니어링에서 AI-native 제품 오너십으로",
    careerIntro: "기술 기반과 창업가적 제품 발견, B2B 성장, AI 제품 사업화를 거쳐 AI와 함께 일하는 제품 개발 체계로 확장해 왔습니다.",
    careers: [
      ["2026.01–현재", "EVAR", "서비스기획·Product Owner → AX Platform 사업 T/F Lead"],
      ["2025.01–2026.01", "SOOJIB", "AI Product Owner & Business Development"],
      ["2024.01–2024.09", "마카롱팩토리", "파트너 전략팀 PO Lead"],
      ["2021.06–2024.01", "어텀팔콘스", "Founder / Product Lead"],
      ["2020.08–2021.06", "현대자동차", "시스템 개발 PM"],
    ],
    recognition: {
      eyebrow: "RECOGNITION & LEADERSHIP",
      title: "제품 성과 밖에서도 증명한 실행과 팀 리더십",
      intro: "AI 제품 사업화, 기술 문제 해결, 그리고 팀 스포츠에서의 리더십까지—서로 다른 환경에서 결과를 만든 기록입니다.",
      items: [
        { year: "2025", type: "PRODUCT AWARD", title: "L’Oréal BigBang 2025 · Digital Winner", desc: "GAN 기반 가상 메이크업 제품의 3CE 협업과 글로벌 PoC를 이끌어 디지털 부문 Winner로 선정됐습니다.", image: "/img/bigbang-startup.jpg", alt: "L’Oréal BigBang 2025 수상 현장", href: "https://www.loreal.com/ko-kr/korea/loreal-korea-news/press-releases/kstartup-frenchtech-bigbang-2025/", link: "공식 기사" },
        { year: "2017", type: "TECH AWARD", title: "Hyundai Hack A Road · 1위", desc: "초보 운전자를 위한 실시간 차량 데이터 조언 시스템을 기획하고 Python 데모를 구현해 대상을 수상했습니다.", image: "/img/hyundai_hack_a_road.jpg", alt: "현대자동차 Hack A Road 수상", href: "https://www.ksilbo.co.kr/news/articleView.html?idxno=621362", link: "관련 기사" },
        { year: "2016", type: "TEAM LEADERSHIP", title: "제11회 대학조정대회 · 종합 3위", desc: "UNIST 조정부 활동을 통해 제11회 대학조정대회에 출전했고, 팀과 함께 대학 종합 3위를 달성했습니다.", image: "/img/rowing.jpg", alt: "UNIST 조정부 대학조정대회 출전 팀", href: "https://news.unist.ac.kr/kor/20160802-03/", link: "UNIST 기사" },
      ],
    },
    closing: {
      eyebrow: "WHY JUNSEOK KIM",
      title: "소수정예 팀의 제품 실행과 비즈니스 성과",
      body: "문제를 선명하게 정의하고 필요한 것을 직접 만듭니다. 출시한 뒤에는 운영 지표로 돌아가 다음 결정을 내립니다.",
      button: "대화 시작하기",
    },
    footnote: "성과 수치는 Career DB의 검증 자료와 사용자 제공 스냅샷을 기준으로 작성했습니다.",
  },
  en: {
    localeName: "English",
    switchLabel: "KO",
    switchHref: "/",
    nav: { work: "Work", approach: "Approach", career: "Career", recognition: "Recognition", contact: "Contact" },
    hero: {
      eyebrow: "Founder-minded, AI-native Product Owner",
      title: "Junseok Kim",
      body: "I own products from problem definition through launch and operations, using AI to help lean teams move faster without losing rigor.",
      primary: "View selected work",
      secondary: "LinkedIn",
      status: "EVAR · AX Platform Business TF Lead",
    },
    impacts: [
      { value: "2w→1w", label: "AI-DLC release cycle", note: "Planning, build and QA in parallel" },
      { value: "~4×", label: "Delivery per person", note: "Estimate based on user-provided inputs" },
      { value: "+582%", label: "Non-UK sales", note: "Cross-border operations expansion" },
      { value: "Winner", label: "L’Oréal BigBang 2025", note: "Digital category" },
    ],
    approach: {
      eyebrow: "PRODUCT OPERATING MODEL",
      title: "From problem definition to operating impact",
      intro: "I go beyond strategy documents by connecting product decisions, implementation, release, and measurement in one delivery loop.",
      items: [
        ["01", "Define", "Combine data, VoC, and interviews to find the structural problem behind recurring symptoms."],
        ["02", "Build", "Make decisions explicit in User Stories and HTML Specs, then execute with AI, prototypes, and code."],
        ["03", "Scale", "Connect releases to operating and business KPIs, turning learnings into reusable product systems."],
      ],
    },
    selected: "Selected work",
    projectIntro: "The cases start with my current scope and trace the product ownership that led here.",
    projects: [
      {
        id: "ai-dlc", company: "EVAR · 2026", label: "FLAGSHIP · DELIVERY SYSTEM", title: "Weekly releases after a 50% team reduction",
        summary: "I designed an AI-DLC operating model that gives product, design, engineering, and QA a shared source of truth for EV PAY and NOVA, EVAR’s charging-operations platform.",
        bullets: ["358 User Stories managed in one system", "90%+ reduction in planning omissions", "Shift from two-week sprints to weekly releases"],
        image: "/img/portfolio/evar/ai-dlc-before-after.png", imageAlt: "Transition from a human-centered two-week sprint to an AI-centered weekly sprint", metric: "~4×", metricLabel: "Estimated delivery per person",
      },
      {
        id: "nova", company: "EVAR · 2026", label: "B2B SAAS · PRODUCT OWNERSHIP", title: "Turning a charging operations tool into multi-tenant SaaS",
        summary: "As NOVA’s lead PM, I redesigned dashboard, charger, revenue, settlement, and permission workflows, then built the foundation for customer migrations in Korea, the US, and Japan.",
        bullets: ["Expanded charger status from 2 to 7 states", "Combined revenue and operations KPIs", "~30% operating efficiency gain (user-provided)"],
        image: "/img/portfolio/evar/nova-dashboard-before-after.png", imageAlt: "Comparison of the EVSquare 1.0 and NOVA dashboards", metric: "358", metricLabel: "User Stories in one backlog",
      },
      {
        id: "ai-call-center", company: "EVAR · IN PROGRESS", label: "AI PRODUCT · DOMAIN ONTOLOGY", title: "AI that reasons about support context, not just documents",
        summary: "I brought hardware, app, and charging-operations documentation into one knowledge model, mapping the relationships among members, credentials, charging assets, and payment events.",
        bullets: ["AX Platform Business TF Lead", "Connected domain entities to lookup rules", "In progress; no outcome metric claimed"],
        image: "", imageAlt: "Public abstraction of an EV charging support ontology with internal entities and decision rules omitted", metric: "Ontology", metricLabel: "Charging-domain knowledge layer",
      },
      {
        id: "hands-on", company: "EVAR · 2026", label: "HANDS-ON BUILDING", title: "Connecting product decisions directly to code and launch",
        summary: "Using AI-assisted development, I built EVAR’s global corporate site end to end and shipped Sticker Studio, a web-based charger customization tool, in two weeks.",
        bullets: ["Korean, English, and Japanese site delivery", "More than 2× inbound leads", "~25% of buyers added the sticker option"],
        image: "/img/portfolio/evar/sticker-studio.png", imageAlt: "EVAR Sticker Studio editor", metric: "2 weeks", metricLabel: "Sticker Studio launch",
      },
      {
        id: "commerce", company: "SOOJIB · 2025", label: "CROSS-BORDER COMMERCE · 0→1", title: "A cross-border operating system across six-plus markets",
        summary: "I built the operating flow from Shopify orders to DHL and FedEx shipping, country- and weight-based rates, and IOSS handling for EU VAT and duties.",
        bullets: ["Annual sales grew approximately 3×", "Non-UK sales increased 582%", "Documented the workflow and handed it over to SCM operations"],
        image: "", imageAlt: "Public summary of the cross-border commerce workflow and growth metrics with personal and commercial details removed", metric: "3×", metricLabel: "Annual sales, 2024→2025",
      },
      {
        id: "sefy", company: "SOOJIB · 2025", label: "AI BEAUTY · GLOBAL POC", title: "Turning AI beauty technology into a brand collaboration",
        summary: "I turned a GAN-based makeup technology into a virtual try-on concept built around K-pop photo cards, aligning the pilot across L’Oréal Korea and China, 3CE, and our engineering team.",
        bullets: ["GAN-powered virtual makeup product", "Global partnership and PoC coordination", "L’Oréal BigBang 2025 Digital Winner"],
        image: "/img/portfolio/soojib/sefy-flow.png", imageAlt: "SEFY virtual idol makeup product flow", metric: "Winner", metricLabel: "L’Oréal BigBang 2025",
      },
      {
        id: "mycle", company: "MYCLE · 2024", label: "B2B GROWTH · PARTNER PRODUCT", title: "Turning a 96.7% drop-off into a partner growth system",
        summary: "I connected the free customer-acquisition proposition, partner landing flow, CRM, and operating ownership to drive acquisition and transaction growth.",
        bullets: ["Session-to-application conversion +361%", "Partner network grew from ~1,000 to 1,700", "Engine-oil service transaction revenue grew from KRW 20B to 30B"],
        image: "/img/portfolio/macarong/partner-landing.jpg", imageAlt: "MYCLE partner application experience", metric: "+70%", metricLabel: "Partner network growth",
      },
    ],
    moreTitle: "Foundations of product ownership",
    more: [
      { period: "2021.06–2024.01", company: "Autumn Falcons", role: "Founder / Product Lead", desc: "Defined 93 problems and ran 15+ MVP and pivot experiments. Klang reached 4,000 users and 17-minute average time spent; FEED100 reached 65% CTA conversion." },
      { period: "2020.08–2021.06", company: "Hyundai Motor Company", role: "System Development PM", desc: "Managed requirements and supplier issues for the Grandeur (GN7) digital cluster platform and reduced repeated validation time by 20% through Python automation." },
    ],
    careerTitle: "From engineering to AI-native product ownership",
    careerIntro: "My path spans systems engineering, founder-led product discovery, B2B growth, AI commercialization, and the design of an AI-native delivery system.",
    careers: [
      ["2026.01–Present", "EVAR", "Product Owner → AX Platform Business TF Lead"],
      ["2025.01–2026.01", "SOOJIB", "AI Product Owner & Business Development"],
      ["2024.01–2024.09", "MYCLE", "Partner Strategy PO Lead"],
      ["2021.06–2024.01", "Autumn Falcons", "Founder / Product Lead"],
      ["2020.08–2021.06", "Hyundai Motor Company", "System Development PM"],
    ],
    recognition: {
      eyebrow: "RECOGNITION & LEADERSHIP",
      title: "Execution and leadership beyond product metrics",
      intro: "A record of delivering results across AI commercialization, technical problem-solving, and team sport.",
      items: [
        { year: "2025", type: "PRODUCT AWARD", title: "L’Oréal BigBang 2025 · Digital Winner", desc: "Led the 3CE collaboration and global PoC for a GAN-powered virtual makeup product, earning the Digital category award.", image: "/img/bigbang-startup.jpg", alt: "L’Oréal BigBang 2025 award ceremony", href: "https://www.loreal.com/ko-kr/korea/loreal-korea-news/press-releases/kstartup-frenchtech-bigbang-2025/", link: "Official article" },
        { year: "2017", type: "TECH AWARD", title: "Hyundai Hack A Road · 1st Place", desc: "Designed a real-time vehicle-data guidance system for novice drivers and implemented its Python demo, winning the grand prize.", image: "/img/hyundai_hack_a_road.jpg", alt: "Hyundai Hack A Road award", href: "https://www.ksilbo.co.kr/news/articleView.html?idxno=621362", link: "Read article" },
        { year: "2016", type: "TEAM LEADERSHIP", title: "11th Inter-University Rowing Competition · 3rd Overall", desc: "Competed as part of the UNIST rowing team and helped the university finish third overall.", image: "/img/rowing.jpg", alt: "UNIST rowing team at the inter-university competition", href: "https://news.unist.ac.kr/kor/20160802-03/", link: "UNIST article" },
      ],
    },
    closing: {
      eyebrow: "WHY JUNSEOK KIM",
      title: "Product execution and business outcomes for lean teams",
      body: "I clarify the problem, build what the team needs, and use operating data to decide what comes next.",
      button: "Start a conversation",
    },
    footnote: "Metrics are based on verified Career DB evidence and dated user-provided snapshots.",
  },
} as const;
