export type Locale = "ko" | "en";

export const copy = {
  ko: {
    localeName: "한국어",
    switchLabel: "EN",
    switchHref: "/en",
    nav: { work: "프로젝트", approach: "일하는 방식", career: "경력", contact: "연락하기" },
    hero: {
      eyebrow: "AI-NATIVE PRODUCT OWNER · PRODUCT BUILDER",
      title: "모호한 문제를\n출시 가능한 제품으로",
      body: "고객 문제의 정의부터 제품 출시와 운영 성과까지 연결합니다. AI와 직접 만드는 실행력을 결합해 소수정예 팀의 속도와 밀도를 높입니다.",
      primary: "대표 프로젝트 보기",
      secondary: "LinkedIn",
      status: "EVAR · AX Platform 사업 T/F Lead",
    },
    impacts: [
      { value: "2주→1주", label: "AI-DLC 배포 주기", note: "기획·개발·QA 병렬 실행" },
      { value: "약 4배", label: "인당 딜리버리 생산성", note: "사용자 제공 산식 기반 추정" },
      { value: "+361%", label: "파트너 입점 전환", note: "마카롱팩토리 퍼널 개선" },
      { value: "Winner", label: "L’Oréal BigBang 2025", note: "디지털 부문" },
    ],
    approach: {
      eyebrow: "PRODUCT OPERATING MODEL",
      title: "문제 정의에서 운영 성과까지",
      intro: "전략 문서에서 멈추지 않고, 제품의 의사결정과 구현·배포·측정을 하나의 흐름으로 연결합니다.",
      items: [
        ["01", "문제 정의", "데이터·VoC·인터뷰를 결합해 반복되는 증상보다 해결해야 할 구조를 찾습니다."],
        ["02", "제품 빌딩", "User Story와 HTML Spec으로 결정을 명시하고 AI·프로토타입·코드로 실행합니다."],
        ["03", "성과 확장", "릴리즈 이후 운영·사업 KPI를 확인해 재사용 가능한 제품 시스템으로 만듭니다."],
      ],
    },
    selected: "대표 프로젝트",
    projectIntro: "현재 역할과 가장 가까운 사례부터, 제품 오너십이 축적된 흐름으로 구성했습니다.",
    projects: [
      {
        id: "ai-dlc",
        company: "EVAR · 2026",
        label: "FLAGSHIP · DELIVERY SYSTEM",
        title: "절반의 인력에서도 배포 빈도 2배",
        summary: "EV PAY와 충전 운영 백오피스(NOVA)의 기획·디자인·개발·QA가 같은 HTML Spec을 보는 AI-DLC 체계를 설계했습니다.",
        bullets: ["358건 User Story 통합 관리", "기획 누락 90% 이상 감소", "2주 스프린트를 주 1회 배포 체계로 전환"],
        image: "/img/portfolio/evar/ai-dlc-before-after.png",
        imageAlt: "사람 중심 2주 스프린트에서 AI 중심 1주 스프린트로 전환한 개발 구조",
        metric: "약 4배",
        metricLabel: "인당 딜리버리 생산성 추정",
      },
      {
        id: "nova",
        company: "EVAR · 2026",
        label: "B2B SAAS · PRODUCT OWNERSHIP",
        title: "충전 운영 도구를 멀티 고객사형 SaaS로",
        summary: "NOVA 리드 PM으로 대시보드·충전 관리·매출·정산·권한 흐름을 재설계하고 국내·미국·일본 고객 전환 기반을 구축했습니다.",
        bullets: ["운영 상태 2개에서 7개로 세분화", "매출·운영 KPI를 한 화면에 통합", "운영 효율 약 30% 향상(사용자 제공)"],
        image: "/img/portfolio/evar/nova-dashboard-before-after.png",
        imageAlt: "EVSquare 1.0과 NOVA 대시보드 비교",
        metric: "358",
        metricLabel: "통합 관리 User Story",
      },
      {
        id: "ai-call-center",
        company: "EVAR · IN PROGRESS",
        label: "AI PRODUCT · DOMAIN ONTOLOGY",
        title: "문서 검색을 넘어 문의 맥락을 판별하는 AI",
        summary: "하드웨어·앱·충전 운영 매뉴얼을 집대성하고 회원, 인증 수단, 충전 설비, 결제 이벤트의 관계와 응대 판단 규칙을 온톨로지로 구조화했습니다.",
        bullets: ["AX Platform 사업 T/F 리드", "도메인 엔터티와 조회 규칙 연결", "진행 중 과제로 성과 수치 미표기"],
        image: "/img/portfolio/evar/ai-call-center-ontology.png",
        imageAlt: "EVAR AI 콜센터 도메인 온톨로지 개념도",
        metric: "Ontology",
        metricLabel: "충전 도메인 지식 구조",
      },
      {
        id: "hands-on",
        company: "EVAR · 2026",
        label: "HANDS-ON BUILDING",
        title: "기획에서 코드와 배포까지 직접 연결",
        summary: "AI 기반 바이브 코딩으로 글로벌 홈페이지를 단독 개발하고, 충전기 커스텀 편집 서비스 Sticker Studio를 2주 만에 출시했습니다.",
        bullets: ["KR·EN·JP 글로벌 홈페이지 구축", "인바운드 리드 2배 이상", "구매자의 약 25%가 스티커 옵션 추가"],
        image: "/img/portfolio/evar/sticker-studio.png",
        imageAlt: "EVAR Sticker Studio 편집 화면",
        metric: "2주",
        metricLabel: "Sticker Studio 출시",
      },
      {
        id: "sefy",
        company: "SOOJIB · 2025",
        label: "AI BEAUTY · GLOBAL POC",
        title: "AI 뷰티 기술을 브랜드 협업 제품으로",
        summary: "아이돌 포토카드 이미지를 활용한 가상 메이크업 경험을 기획하고 L’Oréal Korea·China, 3CE, 개발팀 사이의 제품 요구사항과 PoC를 조율했습니다.",
        bullets: ["GAN 기반 가상 메이크업 제품 기획", "글로벌 파트너십·PoC 운영", "L’Oréal BigBang 2025 디지털 부문 Winner"],
        image: "/img/portfolio/soojib/sefy-flow.png",
        imageAlt: "SEFY 아이돌 메이크업 가상 체험 제품 흐름",
        metric: "Winner",
        metricLabel: "L’Oréal BigBang 2025",
      },
      {
        id: "mycle",
        company: "마카롱팩토리 · 2024",
        label: "B2B GROWTH · PARTNER PRODUCT",
        title: "96.7%가 이탈하던 입점 퍼널을 성장 시스템으로",
        summary: "무료 고객 유치 USP, 입점 랜딩, CRM과 운영 R&R을 연결해 파트너 확보와 거래 성장을 만들었습니다.",
        bullets: ["세션→입점 신청 전환 +361%", "파트너 네트워크 약 1,000→1,700개", "엔진오일 거래 매출 200억→300억원"],
        image: "/img/portfolio/macarong/partner-landing.jpg",
        imageAlt: "마이클 파트너 입점 신청 화면",
        metric: "+70%",
        metricLabel: "파트너 네트워크",
      },
    ],
    moreTitle: "제품 오너십의 기반",
    more: [
      { period: "2021.06–2024.01", company: "어텀팔콘스", role: "Founder / Product Lead", desc: "93개 문제 정의, 15회 이상 MVP·피벗. Klang 4,000명·평균 체류 17분, FEED100 CTA 전환율 65%." },
      { period: "2020.08–2021.06", company: "현대자동차", role: "시스템 개발 PM", desc: "그랜저(GN7) 디지털 계기판 플랫폼의 요구사항·협력사 이슈를 관리하고 Python 테스트 자동화로 검증 시간 20% 단축." },
    ],
    careerTitle: "Engineering에서 AI-native 제품 오너십으로",
    careerIntro: "기술 기반, 창업가적 제품 발견, B2B 성장, AI 제품 사업화를 거쳐 AI가 참여하는 제품 개발 체계로 확장했습니다.",
    careers: [
      ["2026.01–현재", "EVAR", "서비스기획·Product Owner → AX Platform 사업 T/F Lead"],
      ["2025.01–2026.01", "SOOJIB", "AI Product Owner & Business Development"],
      ["2024.01–2024.09", "마카롱팩토리", "파트너 전략팀 PO Lead"],
      ["2021.06–2024.01", "어텀팔콘스", "Founder / Product Lead"],
      ["2020.08–2021.06", "현대자동차", "시스템 개발 PM"],
    ],
    closing: {
      eyebrow: "WHY JUNSEOK KIM",
      title: "소수정예 팀의 제품 실행과 비즈니스 성과",
      body: "문제를 선명하게 정의하고, 필요한 것을 직접 만들며, 출시를 운영 지표와 연결하는 Product Owner입니다.",
      button: "대화 시작하기",
    },
    footnote: "성과 수치는 Career DB의 검증 자료와 사용자 제공 스냅샷을 기준으로 작성했습니다.",
  },
  en: {
    localeName: "English",
    switchLabel: "KO",
    switchHref: "/",
    nav: { work: "Work", approach: "Approach", career: "Career", contact: "Contact" },
    hero: {
      eyebrow: "AI-NATIVE PRODUCT OWNER · PRODUCT BUILDER",
      title: "Turning ambiguity into\nproducts that ship",
      body: "I connect customer problems to shipped products and operating outcomes. By pairing AI-native delivery with hands-on building, I help small teams move faster with greater rigor.",
      primary: "View selected work",
      secondary: "LinkedIn",
      status: "EVAR · AX Platform Business TF Lead",
    },
    impacts: [
      { value: "2w→1w", label: "AI-DLC release cycle", note: "Planning, build and QA in parallel" },
      { value: "~4×", label: "Delivery per person", note: "Estimate based on user-provided inputs" },
      { value: "+361%", label: "Partner conversion", note: "MYCLE onboarding funnel" },
      { value: "Winner", label: "L’Oréal BigBang 2025", note: "Digital category" },
    ],
    approach: {
      eyebrow: "PRODUCT OPERATING MODEL",
      title: "From problem definition to operating impact",
      intro: "I go beyond strategy documents by connecting product decisions, implementation, release, and measurement in one delivery loop.",
      items: [
        ["01", "Define", "Combine data, VoC, and interviews to find the structural problem behind recurring symptoms."],
        ["02", "Build", "Make decisions explicit in User Stories and HTML Specs, then execute with AI, prototypes, and code."],
        ["03", "Scale", "Connect releases to operating and business KPIs, turning learnings into reusable product systems."],
      ],
    },
    selected: "Selected work",
    projectIntro: "The cases start with my current scope and trace the product ownership that led here.",
    projects: [
      {
        id: "ai-dlc", company: "EVAR · 2026", label: "FLAGSHIP · DELIVERY SYSTEM", title: "Twice the release frequency with half the team",
        summary: "I designed an AI-DLC operating model where planning, design, engineering, and QA work from the same HTML Specs for EV PAY and the NOVA charging back office.",
        bullets: ["358 User Stories managed in one system", "90%+ reduction in planning omissions", "Shift from two-week sprints to weekly releases"],
        image: "/img/portfolio/evar/ai-dlc-before-after.png", imageAlt: "Transition from a human-centered two-week sprint to an AI-centered weekly sprint", metric: "~4×", metricLabel: "Estimated delivery per person",
      },
      {
        id: "nova", company: "EVAR · 2026", label: "B2B SAAS · PRODUCT OWNERSHIP", title: "Turning a charging operations tool into multi-tenant SaaS",
        summary: "As lead PM for NOVA, I redesigned dashboard, charger, sales, settlement, and permission workflows while building the foundation for customer migration in Korea, the US, and Japan.",
        bullets: ["Expanded charger status from 2 to 7 states", "Combined revenue and operations KPIs", "~30% operating efficiency gain (user-provided)"],
        image: "/img/portfolio/evar/nova-dashboard-before-after.png", imageAlt: "Comparison of the EVSquare 1.0 and NOVA dashboards", metric: "358", metricLabel: "User Stories in one backlog",
      },
      {
        id: "ai-call-center", company: "EVAR · IN PROGRESS", label: "AI PRODUCT · DOMAIN ONTOLOGY", title: "AI that reasons about support context, not just documents",
        summary: "I consolidated hardware, app, and charging-operations manuals, then modeled the relationships and response rules across members, credentials, charging assets, and payment events.",
        bullets: ["AX Platform Business TF Lead", "Connected domain entities to lookup rules", "In progress; no outcome metric claimed"],
        image: "/img/portfolio/evar/ai-call-center-ontology.png", imageAlt: "Concept map for the EVAR AI support domain ontology", metric: "Ontology", metricLabel: "Charging-domain knowledge layer",
      },
      {
        id: "hands-on", company: "EVAR · 2026", label: "HANDS-ON BUILDING", title: "Connecting product decisions directly to code and launch",
        summary: "I independently built EVAR’s global corporate site with AI-assisted coding and shipped Sticker Studio, a charger customization editor, in two weeks.",
        bullets: ["Korean, English, and Japanese site delivery", "More than 2× inbound leads", "~25% of buyers added the sticker option"],
        image: "/img/portfolio/evar/sticker-studio.png", imageAlt: "EVAR Sticker Studio editor", metric: "2 weeks", metricLabel: "Sticker Studio launch",
      },
      {
        id: "sefy", company: "SOOJIB · 2025", label: "AI BEAUTY · GLOBAL POC", title: "Turning AI beauty technology into a brand collaboration",
        summary: "I shaped a virtual makeup experience using idol photo cards and aligned product requirements and PoC execution across L’Oréal Korea and China, 3CE, and engineering.",
        bullets: ["GAN-powered virtual makeup product", "Global partnership and PoC coordination", "L’Oréal BigBang 2025 Digital Winner"],
        image: "/img/portfolio/soojib/sefy-flow.png", imageAlt: "SEFY virtual idol makeup product flow", metric: "Winner", metricLabel: "L’Oréal BigBang 2025",
      },
      {
        id: "mycle", company: "MYCLE · 2024", label: "B2B GROWTH · PARTNER PRODUCT", title: "Turning a 96.7% drop-off into a partner growth system",
        summary: "I connected the free customer-acquisition proposition, partner landing flow, CRM, and operating ownership to drive acquisition and transaction growth.",
        bullets: ["Session-to-application conversion +361%", "Partner network grew from ~1,000 to 1,700", "Engine-oil transaction revenue grew from KRW 20B to 30B"],
        image: "/img/portfolio/macarong/partner-landing.jpg", imageAlt: "MYCLE partner application experience", metric: "+70%", metricLabel: "Partner network growth",
      },
    ],
    moreTitle: "Foundations of product ownership",
    more: [
      { period: "2021.06–2024.01", company: "Autumn Falcons", role: "Founder / Product Lead", desc: "Defined 93 problems and ran 15+ MVP and pivot experiments. Klang reached 4,000 users and 17-minute average time spent; FEED100 reached 65% CTA conversion." },
      { period: "2020.08–2021.06", company: "Hyundai Motor Company", role: "System Development PM", desc: "Managed requirements and supplier issues for the Grandeur (GN7) digital cluster platform and reduced repeated validation time by 20% through Python automation." },
    ],
    careerTitle: "From engineering to AI-native product ownership",
    careerIntro: "My path combines technical foundations, founder-led discovery, B2B growth, AI product commercialization, and an AI-participatory product delivery system.",
    careers: [
      ["2026.01–Present", "EVAR", "Product Owner → AX Platform Business TF Lead"],
      ["2025.01–2026.01", "SOOJIB", "AI Product Owner & Business Development"],
      ["2024.01–2024.09", "MYCLE", "Partner Strategy PO Lead"],
      ["2021.06–2024.01", "Autumn Falcons", "Founder / Product Lead"],
      ["2020.08–2021.06", "Hyundai Motor Company", "System Development PM"],
    ],
    closing: {
      eyebrow: "WHY JUNSEOK KIM",
      title: "Product execution and business outcomes for lean teams",
      body: "I define the right problem, build what is needed, and connect launches to operating metrics.",
      button: "Start a conversation",
    },
    footnote: "Metrics are based on verified Career DB evidence and dated user-provided snapshots.",
  },
} as const;
